# 🦉COSADAMA Introduction to Data Science Study

- 작성자: 박하람 
- 참고자료: 파이썬 머신러닝 완벽가이드(권철민), 비쥬얼프로그래밍 수업(김승태), 파이썬으로 데이터 주무르기(민형기)

## 2. What are NumPy, matplotlib?

이번 주차에는 **수치 데이터 처리 모듈 Numpy, 시각화 모듈 matplotlib**의 간단한 문법을 학습하려 합니다. 프로젝트를 먼저 실시하기에 앞서 이러한 모듈들을 어느정도 학습하는 것이 여러분들에게 더 도움이 되겠다 판단하여 아주 간단하게 모두를 다뤄보겠습니다.

### 2.1 수치 데이터 처리 - NumPy

NumPy는 데이터/수치 분석 모듈로 Numerical Python을 의미합니다. 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지입니다. 루프(loop)를 사용하지 않고 대량 데이터의 배열 연산을 가능하게 하므로 빠른 배열 연산 속도를 보장합니다. 대량 데이터 기반의 과학과 공학 프로그램은 빠른 계산 능력이 매우 중요합니다. 때문에 파이썬 기반의 많은 과학과 공학 패키지는 넘파이에 의존하고 있습니다. 그러나 **수학 연산을 돕는 도구이지, 분석 도구는 아닙니다.** 넘파이는 내용이 상당히 방대하니 넘파이를 정복하겠다는 생각은 하지 맙시다. 데이터 분석에 우선적으로 필요한 부분만 최대한 빨리 학습하여 부족한 부분은 후에 채워가면서 학습하면 됩니다. 

아, **과제 문제가 3개 있으니 잊지 말고 제출해 주세요!**

#### NumPy import 하기 

In [1]:
import numpy as np

#### 다차원 배열 ndarray 
- NumPy의 중요 자료형 
- 표준 파이썬의 array와 비슷하지만 별개임
- 다차원(Multi-dimentsion) 배열을 쉽게 생성하고 다양한 연산을 수행할 수 있음.

In [2]:
list1 = [1,2,3]
print(type(list1))   # 파이썬의 list
array1 = np.array(list1)
print(type(array1))  # 넘파이의 ndarray

<class 'list'>
<class 'numpy.ndarray'>


- array() 함수는 파이썬의 리스트와 같은 다양한 인자를 입력 받아서 ndarray로 변환하는 기능을 수행. 
- 생성된 ndarray 배열의 shape 변수는 ndarray의 크리, 즉 행과 열의 수를 튜플 형태로 가지고 있으며 이를 통해 ndarray 배열의 차원까지 알 수 있음.

In [3]:
array1 = np.array([1,2,3])
array1

array([1, 2, 3])

In [4]:
type(array1)

numpy.ndarray

In [5]:
array1.shape # 쉼표 뒤가 없다면 1차원이라는 의미 

(3,)

In [6]:
# 2차원 ndarray 만들기 
array2 = np.array([[1,2,3],
                 [2,3,4]])
array2   # 항상 데이터를 보는 습관 들이기!

array([[1, 2, 3],
       [2, 3, 4]])

In [7]:
type(array2)

numpy.ndarray

In [8]:
array2.shape # 2개의 row와 3개의 column

(2, 3)

#### ndarray의 중요 속성
- **ndarray.ndim** : ndarray의 차원
- **ndarray.shape**: 배열의 모양 
- **ndarray.size**: 배열의 원소의 개수 
- **ndarray.dtype** : 원소의 자료형

In [9]:
array1.ndim  # 1차원이구나!

1

In [10]:
array2.ndim # 2차원이구나!

2

In [11]:
array1.size

3

In [12]:
array2.size

6

In [13]:
array1.dtype

dtype('int32')

#### 배열 생성하기 

- [numpy의 random 모듈 학습](https://nittaku.tistory.com/443)

In [14]:
data = np.random.randn(2,3) #0에서 1사이의 균일 분포에서 난수 생성
data # 항상 이렇게 변수명을 적어 데이터가 어떻게 나오는지 보는 습관 들이기!

array([[ 0.33657423,  0.89653759, -2.11299124],
       [-0.33322897, -0.58722101, -1.4667888 ]])

In [15]:
data * 10

array([[  3.36574235,   8.96537594, -21.1299124 ],
       [ -3.33228973,  -5.87221009, -14.66788802]])

In [16]:
data + data # 배열 더하기

array([[ 0.67314847,  1.79307519, -4.22598248],
       [-0.66645795, -1.17444202, -2.9335776 ]])

In [17]:
# ndarray 배열의 모양 즉, 2개의 row와 3개의 column으로 구성
data.shape 

(2, 3)

In [18]:
# 차원의 수
data.ndim

2

#### 배열 생성 array 함수
- **array()**: 데이터를 기반으로 배열(ndarray)를 생성하는 함수

In [19]:
alist = [1,2.5,3,4.5,5]
arr1 = np.array(alist) # ndarray로 바꾸어준 것!
arr1

array([1. , 2.5, 3. , 4.5, 5. ])

In [20]:
dalist = [[1,2,3,4,5],
         [6,7,8,9,10]]
arr2 = np.array(dalist)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

#### ndarray를 편리하게 생성하기 - arange, zeros, ones

특정 크기와 차원을 가진 ndarray를 연속값이나 0또는 1로 초기화해 쉽게 생성해야 할 필요가 있는 경우가 발생할 수 있음. 이 경우 **arange(), zeros(), ones()**를 이용해 쉽게 ndarray를 생성할 수 있음.

- **np.arange()**: range의 numpy 버전. 0부터 함수 인자 값 -1까지의 값을 순차적으로 ndarray의 데이터값으로 변환해줌.
- **np.zeros()**: 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 0으로 채운 해당 shape를 가진 ndarray를 반환함. 
- **np.ones()**: 함수 인자로 튜플 형태의 shape 값을 입력하면 모든 값을 1로 채운 해당 shape을 가진 ndarray를 반환함.

In [21]:
# 꿀팁! 내가 잘 모르는 게 나왔다! 
np.arange?

이렇게 괄호 대신 **?**를 적어주면 도움말이 뜹니다! 그러면 영어로 옵션값(파라미터들)도 볼 수 있고, 어떤 함수인지도 알 수 있습니다. 무엇보다 가장 좋은 것은 제일 아래에 **examples**를 통해 이 함수가 어떤 기능을 하는지 직관적으로 알 수 있어요! 

In [22]:
# 예시를 하나 가져왔어요. 아, 이 함수는 파이썬의 range()와 비슷하구나~
np.arange(3)

array([0, 1, 2])

In [23]:
sequence_array = np.arange(10)
sequence_array  # 항상 데이터 확인하는 것 잊지말기!

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
sequence_array.shape  # 1차원이고, 칼럼이 10개네~!

(10,)

In [25]:
# 이 3개짜리는 무엇을 의미할까요?
question = np.arange(0,10,2)
question

array([0, 2, 4, 6, 8])

In [26]:
zero_array = np.zeros((3,2), dtype='int32')
zero_array

array([[0, 0],
       [0, 0],
       [0, 0]])

In [27]:
zero_array.shape

(3, 2)

In [28]:
one_array = np.ones((3,2))
one_array

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [29]:
one_array.shape

(3, 2)

#### ndarray의 차원과 크기를 변경하는 reshape()

- **np.reshape()**: ndarray를 특정 차원 및 크기로 변환 

In [30]:
b = np.arange(12).reshape(4,3) # 4개의 로우, 3개의 컬럼으로!
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [31]:
c = np.arange(24).reshape(2,3,4) # 3차원으로 바꿔주세욤!
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

#### 수학 개념 함수 / 통계용 메서드들
- sum(): 전체 또는 특정 축의 원소의 합계
- mean(): 산술평균
- std(): 표준편차
- var(): 분산
- min(), max(): 최소값, 최대값
- cumsum(): 누적합
- comprod(): 누적곱


In [32]:
a = np.random.random((2,3))
a

array([[0.30804036, 0.70411508, 0.08159497],
       [0.43746412, 0.5387499 , 0.32312268]])

In [33]:
a.sum()

2.3930871116957118

In [34]:
a.min()

0.08159497080581557

In [35]:
a.max()

0.7041150766704284

In [36]:
a.sum(axis=0)   # 열의 합(아래 방향)

array([0.74550449, 1.24286497, 0.40471765])

In [37]:
a.sum(axis=1)   # 행의 합(오른쪽 방향)

array([1.09375041, 1.2993367 ])

In [38]:
a.cumsum(axis=1)  # 행의 누적합

array([[0.30804036, 1.01215544, 1.09375041],
       [0.43746412, 0.97621402, 1.2993367 ]])

In [39]:
arr = np.array([[0,1,2],
              [3,4,5],
              [6,7,8]])
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [40]:
arr.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [41]:
arr.cumsum(axis = 1) # column 방향으로~

array([[ 0,  1,  3],
       [ 3,  7, 12],
       [ 6, 13, 21]], dtype=int32)

질문이 들어왔는데요, numpy에서 axis=0은 row, axis=1은 column을 의미합니다. 그래서 column 방향이라고 한 것에 헷갈릴 수 있겠지만, 틀린 말이 아닙니다. 참고하세요~!

#### Indexing 

- 기본적으로 list와 같은 방식

In [42]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [43]:
a[2]

8

In [44]:
a[2:5]

array([ 8, 27, 64], dtype=int32)

In [45]:
a[:6:2] = -1000  #a[0:6:2]에 모두 -1000을 넣는다
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,
         729], dtype=int32)

In [46]:
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1,
       -1000], dtype=int32)

In [47]:
# 다차원 ndarray의 인덱싱 
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr2d[2]

array([7, 8, 9])

In [48]:
arr2d[0,2]

3

####  Slicing

In [49]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
arr_slice = arr[5:8]
arr_slice

array([5, 6, 7])

In [51]:
# 다차원 ndarray의 슬라이싱
arr2d = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [52]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [53]:
arr2d[:2,1:]  # 생략 되어 있다면 0부터!

array([[2, 3],
       [5, 6]])

#### Boolean Indexing
- 조건 필터링과 검색을 동시에 할 수 있어 매우 자주 이용되는 인덱싱 방식

In [54]:
array1d = np.arange(start=1, stop=10) #(1,10)과 같음
array1d

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# [ ] 안에 array1d > 5보다 높은 것만 가져오너라!
boolean_array1d = array1d[array1d > 5]
boolean_array1d

array([6, 7, 8, 9])

In [56]:
array1d > 5 # 5이상이면 True로 표시

array([False, False, False, False, False,  True,  True,  True,  True])

#### 난수 생성 
- np.random.rand(): 균등 분포에서 추철 
- np.random.randint(): 주어진 범위 내의 임의의 난수 
- np.random.randn(): 표준편차가 1이고 평균 0인 정규 분포에서 추출 
- np.random.normal(): 정규 분포에서 추출

In [57]:
a = np.random.normal(size=(4,4))
a

array([[ 0.15947163, -0.10381295, -1.40611371, -0.83275307],
       [ 0.38743887, -0.74626072, -0.77014419,  0.0822977 ],
       [-0.0492367 , -0.97997549, -0.22625832,  0.36076559],
       [ 0.82263307, -0.33873647,  1.56631342, -0.97812027]])

In [58]:
b = np.random.randn(4,4)
b

array([[-1.69453078, -0.77045282,  0.07073747, -0.51623367],
       [ 1.17230171, -1.75608976, -1.06318371, -0.28396412],
       [ 1.67912299,  0.26406609,  0.06496775, -1.61263553],
       [-0.19099145, -0.89348338,  1.54734076,  0.74781568]])

#### 실습1: numpy을 왜 사용할까? 

다음 프로그램을 작성해보자. 
- 1 또는 -1의 값을 랜덤하게 생성한다. 1이 나오면 한 칸 전진하고 -1이 나오면 한 칸 후진한다. 
- 이 과정을 1000회 반복한다. 그 때 나의 위치는 어디인가? 

In [59]:
# numpy를 모르고 파이썬 프로그래밍만으로 만들 때 
import random
position = 0
walk = [position]
for i in range(1000):
    step = 1 if random.randint(0,1) else -1
    position + step
    walk.append(position)

이것을 numpy 버전으로 만드시오. 단, 변수는 draws, steps, walk 이 3가지만 사용하여야 한다.

#### 실습2: numpy를 왜 사용할까? 
𝒚 = 𝒙^𝟑 +𝟑𝒙^𝟐 +𝟑𝒙 + 𝟏의 그래프를 그려라. x와 y에 값을 넣어 에러를 해결하세요!

In [60]:
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

x = _________
y = _________

df = pd.DataFrame(x,y)
plt.plot(df)

NameError: name '_________' is not defined

여기까지가 수치 데이터 처리에 사용되는 NumPy였습니다! 
지금 바로 당장에는 사용하지 않을 것 같아요. 당장에 많이 사용되는 것은 pandas겠지만 그래도 pandas 배우는 김에 numpy도 배우고 넘어가야하지 않겠어요. 

**과제방에 실습 1,2를 올려주시면 됩니다!**